### PR TITLE
adding the possibility to transmit worker options to the worker factory

### PR DESCRIPTION
**Pull request by AlexandreDecollas**
It's probably better and simpler to do this way :p 

So this PR only gives the ability to add options to the user while using the BullMQModule to provide all the options a worker can have in bullmq

### CODE REVIEW

**Comment by AlexandreDecollas** [comment]
@xdave Could you check it if you have a minute please? We need this feature in my team

**Comment by xdave** [comment]
@AlexandreDecollas  I'll merge it

**Comment by AlexandreDecollas** [comment]
Great! thank you very much :) is it possible to upgrade the npm package version with this update please?

**Comment by xdave** [comment]
@AlexandreDecollas  done 3.0.1

**Pull request merged**
